frogs/apps/frogblog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	
	url(r'^$', views.post_list, name='post_list'),
	
]

frogs/apps/surgery/urls.py
from django.conf.urls import patterns, url

from surgery.views import SurgeryCreate, SurgeryDelete, SurgeryDetail, SurgeryList, \
    SurgeryUpdate

urlpatterns = patterns('',
    url(
        r'^new/$',
        SurgeryCreate.as_view(),
        name='surgery_create'
    ),
    url(
        r'^delete/(?P<pk>\d+)$',
        SurgeryDelete.as_view(),
        name='surgery_delete'
    ),
    url(
        r'^(?P<pk>\d+?)$',
        SurgeryDetail.as_view(),
        name='surgery_detail'
    ),
    url(
        r'^update/(?P<pk>\d+)$',
        SurgeryUpdate.as_view(),
        name='surgery_update'
    ),
    url(
        r'^$',
        SurgeryList.as_view(),
        name='surgery_list'
    ),
)

frogs/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

import frogblog.urls
import surgery.urls


urlpatterns = [
    # Examples:
    # url(r'^$', 'tt.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(surgery.urls)),
    url(r'^blog/', include('frogblog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frogs/apps/frogblog/models.py
from __future__ import unicode_literals

from django.db import models

from django.utils import timezone



class Post(models.Model):
	
	author = models.ForeignKey('auth.User')
	
	title = models.CharField(max_length=200)
	
	text = models.TextField()
	
	created_date = models.DateTimeField(
		default=timezone.now)
		
	published_date = models.DateTimeField(
		blank=True, null=True)
		
		
		
	def published (self):
		
		self.published_date = timezone.now()
		
		self.save()
	
	def __str__(self):
		
		return self.title
		

frogs/apps/surgery/models.py
from django.db import models

class Surgery(models.Model):
    surgery_number = models.IntegerField()
    date = models.DateField()
    frog = models.CharField(max_length=200)
    tank_number = models.IntegerField()
    collagenase = models.IntegerField()
    collagenase_amount = models.IntegerField()
    activity = models.IntegerField()
    solution_volume = models.IntegerField()
    g_b_oocytes = models.CharField(max_length=1)
    volume_of_oocytes = models.IntegerField()
    previous_surgery = models.ForeignKey('Surgery', null=True, blank=True)
    company = models.CharField(max_length=200)
    number_oocytes_ordered = models.IntegerField()
    complaints = models.BooleanField()
    notes = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return str(self.surgery_number)

frogs/apps/surgery/forms.py
from django import forms
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.forms import Form, ModelForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import ButtonHolder, Column, Field, Fieldset, \
    Layout, Row, Submit

from surgery.models import Surgery

class SurgeryForm(ModelForm):
    class Meta:
        model = Surgery
        fields = [
            'surgery_number', 'date', 'frog', 'tank_number', 'collagenase', 
            'collagenase_amount', 'activity', 'solution_volume', 'g_b_oocytes', 
            'volume_of_oocytes', 'previous_surgery', 'company', 
            'number_oocytes_ordered', 'complaints', 'notes',
        ]

    def __init__(self, *args, **kwargs):
        super(SurgeryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('surgery_number', css_class="form-control"),
            Field('date', css_class="form-control"),
            Field('frog', css_class="form-control"),
            Field('tank_number', css_class="form-control"),
            Field('collagenase', css_class="form-control"),
            Field('collagenase_amount', css_class="form-control"),
            Field('activity', css_class="form-control"),
            Field('solution_volume', css_class="form-control"),
            Field('g_b_oocytes', css_class="form-control"),
            Field('volume_of_oocytes', css_class="form-control"),
            Field('previous_surgery', css_class="form-control"),
            Field('company', css_class="form-control"),
            Field('number_oocytes_ordered', css_class="form-control"),
            Field('complaints', css_class="form-control"),
            Field('notes', css_class="form-control"),
        )
        self.helper.form_tag = False

frogs/apps/frogblog/views.py
from django.shortcuts import render

from django.utils import timezone

from .models import Post

def post_list(request):
	
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	
	return render(request, 'frogblog/post_list.html', {'posts' : posts})

frogs/apps/surgery/views.py
from django.shortcuts import render

from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, \
    ListView, UpdateView, TemplateView, View

from surgery.forms import SurgeryForm
from surgery.models import Surgery

class SurgeryCreate(CreateView):
    model = Surgery
    form_class = SurgeryForm
    success_url = '/'

class SurgeryDelete(DeleteView):
    model = Surgery
    success_url = '/'

class SurgeryDetail(DetailView):
    model = Surgery

class SurgeryList(ListView):
    model = Surgery
    
class SurgeryUpdate(UpdateView):
    model = Surgery
    form_class = SurgeryForm
    success_url = '/'

    

frogs/templates/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <meta name="description" content="{% block description %}{% endblock %}" />
    <meta name="keywords" content="{% block keywords %}{% endblock %}" />
    <meta name="viewport" content="{% block viewport %}width=device-width"{% endblock %}>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>{% block title %}frogs{% endblock title %}</title>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="icon" type="image/gif" href="{% static 'img/favicon.gif' %}">

    {% block css %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    {% endblock %}

  </head>

  <body>
    <div class="m-b">
        <nav class="navbar navbar-static-top" id="navbar-header">
        <div class="container">
            <ul class="nav navbar-nav navbar-right">
                <li><a class="nav-link nav-item" href="{% url 'surgery_list' %}">View Surgeries</a></li>
                <li><a class="nav-link nav-item" href="{% url 'surgery_create' %}">New Surgery</a></li>
            </ul>
        </div>
        </nav>
    </div>
    <div class="container">

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <script src="{% static 'js/scripts.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>

frogs/templates/frogblog/post_list.html
{% load staticfiles %}
<html>
    <head>
        <title>Frog Blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/frogblog.css' %}">
    </head>
    <body>
        <div>
            <h1><a href="/">Frog Blog</a></h1>
        </div>

        {% for post in posts %}
            <div>
                <p>published: {{ post.published_date }}</p>
                <h1><a href="">{{ post.title }}</a></h1>
                <p>{{ post.text|linebreaks }}</p>
            </div>
        {% endfor %}
    </body>
</html>

frogs/templates/surgery/surgery_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p> Are you sure you want to delete "{{ object}}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock %}
~                                                                                                                                                                                                                                                                             

frogs/templates/surgery/surgery_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}
{% if object.pk %}
    Update Surgery
{% else %}
    Create Surgery
{% endif %}
{% endblock %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
{% endblock %}
{% block content %}
    {% if object.pk %}
        <h2>Update Surgery</h2>
    {% else %}
        <h2>Create Surgery</h2>
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {% crispy form %}
    <input class="btn btn-primary" type="submit" value="Save">

    </form>
{% endblock %}
{% block javascript %}
{{ block.super }}
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script>
    $(function() {
        $( "#id_date" ).datepicker();
    });
</script>
{% endblock %}

frogs/templates/surgery/surgery_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
    Surgeries
{% endblock %}
{% block content %}
<h1>Surgeries</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Surgery Number</th>
            <th>Frog Name</th>
            <th>Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
        <tr>
            <td>{{ object.surgery_number }}</td>
            <td>{{ object.frog }}</td>
            <td>{{ object.date }}</td>
            <td>
                <a href="{% url 'surgery_update' object.pk %}">Edit</a>
                <a href="{% url 'surgery_delete' object.pk %}">Delete</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}